# Generated by Django 4.0.3 on 2024-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(default='', max_length=3),
        ),
    ]
