# Generated by Django 4.0.3 on 2024-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='topic',
            field=models.CharField(default='a', max_length=3),
        ),
    ]
