# Generated by Django 4.0.3 on 2024-03-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_quizz_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='topic',
        ),
        migrations.CreateModel(
            name='SubjectQuizz',
            fields=[
                ('quizz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizz.quizz')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.subject')),
            ],
            bases=('quizz.quizz',),
        ),
        migrations.CreateModel(
            name='QuestionQuizz',
            fields=[
                ('quizz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizz.quizz')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.question')),
            ],
            bases=('quizz.quizz',),
        ),
        migrations.CreateModel(
            name='LectureQuizz',
            fields=[
                ('quizz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizz.quizz')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.lecture')),
            ],
            bases=('quizz.quizz',),
        ),
    ]
