# Generated by Django 4.0.3 on 2024-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_remove_quizz_topic_subjectquizz_questionquizz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='mode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
