# Generated by Django 4.0.3 on 2024-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_quizz_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
