# Generated by Django 4.0.3 on 2024-03-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_quizzmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.quizzmode'),
        ),
    ]
