# Generated by Django 4.0.3 on 2024-03-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_alter_quizz_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='mode',
        ),
    ]
