# Generated by Django 4.0.3 on 2024-03-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0010_remove_quizz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.quizzmode'),
        ),
    ]
