# Generated by Django 4.0.3 on 2024-03-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_quizz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='current_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_question', to='quizz.question'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='questions',
            field=models.ManyToManyField(related_name='quizz_questions', to='quizz.question'),
        ),
    ]
