# Generated by Django 4.0.3 on 2024-03-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0013_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
