# Generated by Django 4.0.3 on 2024-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0014_delete_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
    ]
