# Generated by Django 4.0.3 on 2024-05-22 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0015_alter_subject_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
