# Generated by Django 4.0.3 on 2024-05-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0016_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
