# Generated by Django 4.0.3 on 2024-07-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0017_remove_question_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=511),
        ),
    ]
