# Generated by Django 4.0.3 on 2024-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0019_quizz_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hints',
            field=models.BooleanField(default=True),
        ),
    ]
