# Generated by Django 4.0.3 on 2024-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0021_remove_questionquizz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
