# Generated by Django 4.0.3 on 2024-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0025_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='last_change_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='last_change_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='last_change_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_change_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
