# Generated by Django 4.0.3 on 2024-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0026_lecture_creation_date_lecture_last_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='expected_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='given_answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
