# Generated by Django 4.0.3 on 2024-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0028_quizz_question_time_limit_test_answer_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question_time_limit',
        ),
    ]
