# Generated by Django 4.0.3 on 2024-08-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0030_quizz_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answer_time',
        ),
    ]
