# Generated by Django 4.0.3 on 2024-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0031_remove_test_answer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='timer_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
