# Generated by Django 4.0.3 on 2024-08-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0032_quizz_timer_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='timer_started',
            new_name='timer_active',
        ),
    ]
