# Generated by Django 4.0.3 on 2024-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0033_rename_timer_started_quizz_timer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
    ]
