# Generated by Django 4.0.3 on 2024-08-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0035_quizz_timer_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='timer_active',
        ),
    ]
