# Generated by Django 4.0.3 on 2024-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0036_remove_quizz_timer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
    ]
