# Generated by Django 4.0.3 on 2024-08-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0037_quizz_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='private',
        ),
    ]
