# Generated by Django 4.0.3 on 2024-08-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0039_lecture_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
    ]
