# Generated by Django 4.0.3 on 2024-08-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0040_remove_lecture_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.CharField(default='', max_length=4095),
        ),
        migrations.AddField(
            model_name='quizz',
            name='aicheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='aicheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='timer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.timermode'),
        ),
    ]
